name: CI

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check format
      run: black --diff --color --check jetbrains.py

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint code
      run: pylint jetbrains.py -f colorized -sno --disable=R
